title: Some Person - Photography
description: Description of Project
author: Author Name
author_email: author@email.com
url: https://photosite.netlify.com

exclude:
  - node_modules
  - gulpfile.js
  - fetchContentfulImgs.js
  - package.json
  - Gemfile
  - Gemfile.lock
  - README.md
  - createProjects.rb
  - assets/css/modules
  - assets/css/main.scss
  - assets/images/home/download
  - _projects/README.md

collections:
    projects:
        output: true

contentful:
  spaces:
    - posts:
        space: 4ett0pcl5c14
        access_token: 9c8d0bf69fa1e99c83e68d299437a365b8e8d34d46c41ac7c2c0a5aefb358e18
